server: 
  port: 3344 
  
spring:
  application:
    name:  microservice-config
  cloud:
    config:
      server:
        git: 
          uri: https://github.com/wzylife15/microservice-config.git
          search-paths:
          - microservice-config
          force-pull: true
          
          
          
  
