spring:
  application:
    name: SCW-USER
  datasource:
    username: root
    password: 1
    url: jdbc:mysql://192.168.144.129:3307/crowdfunding?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.144.129
    port: 6379
    #password: 123456
    
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    appname: SCW-USER
    prefer-ip-address: true
    
server:
  port: 7000